spring.application.name=demo
server.port=8081

# H2 Database Settings
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:nexesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.application.name=nexes-ai-platform
server.port=8081

# MongoDB Configuration (NEXES Primary Storage)
spring.data.mongodb.uri=mongodb://localhost:27017/nexes_db
spring.data.mongodb.database=nexes_db

# Security & Cloud Prep
server.error.include-message=always

# MongoDB Atlas Cloud Connection
spring.data.mongodb.uri=mongodb+srv://vinu_admin:Vinusha27@cluster0.pes2xel.mongodb.net/nexes_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=nexes_db

server.port=8081